name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Load .env variables
      run: |
        cat COMPUTER_VISION/.env | grep -v '^#' | xargs -L 1 echo "export " >> $GITHUB_ENV

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build and push Docker image
      run: |
        cd COMPUTER_VISION
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/gradio_app .
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/gradio_app ${{ secrets.DOCKERHUB_USERNAME }}/gradio_app:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/gradio_app:latest

    - name: Login to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      run: |
        az webapp create --resource-group RG_ABADIF --plan myAppServicePlan --name myGradioApp --deployment-container-image-name ${{ secrets.DOCKERHUB_USERNAME }}/gradio_app:latest
        az webapp config container set --name myGradioApp --resource-group RG_ABADIF --docker-custom-image-name ${{ secrets.DOCKERHUB_USERNAME }}/gradio_app:latest
